### ISSUE TITLE
ms-mint-app

### ISSUE THREAD

**Issue by drhilal** [LewisResearchGroup/ms-mint-app#1]
Hello, first of all congratulations for the application. I tried to run the application but got an error. First of all, the application is constantly updating itself in the part with dash. Secondly, when it comes to the upload data part, the following calback error appears.

Callback error updating {"index": "ms-uploader-output", "type": "output"}, "children"
TypeError: expected str, bytes or os.PathLike object, not list
fn_new = P(ms_dir) / P(fn).name
I couldn't run it, it seems to load the data, but it doesn't, giving these errors.

I guess P(fn).name doesn't see it as path.

**Comment by sorenwacker** [comment]
Hi @hilaluzunoglu , and thank you for you interest in the app. We are currently refactoring the code.

How did you install the app? Are you on a Windows or Linux or Mac? And how did you start the app? 

The update notification is normal in older releases. It is the frontend talking to the backend. That will be removed in the coming version. 

If I have time I might create a new release later today. In the mean time there is also the online version available at

https://mint.resistancedb.org/

That can be used to try the app.

**Comment by sorenwacker** [comment]
We switched the uploader to the new prerelease of the dash uploader. 

https://github.com/np-8/dash-uploader

You can insall it with:

     pip install dash-uploader==0.7.0a1 --pre

**Comment by drhilal** [comment]
I am using windows. I got import errors for libraries while running the
application, so I ran it by editing the folders. For example from . import
tools as T was giving an error in such usage, I took the py files under the
folder and pulled from that folder, other than that, I ran the app.py file
via Anaconda prompt. I will reinstall dash-uploader and try. I'm working on
dash too. In order to improve myself, I want to understand the code by
examining it, so I hope I can run it :).

Sören Wacker ***@***.***>, 10 Haz 2022 Cum, 18:56 tarihinde
şunu yazdı:

**Comment by drhilal** [comment]
I wonder if the mzML data I uploaded is not suitable? Also,  I don't have
the target data. Can you send me sample data with mzML and targets so I can
try it.

Hilal UZUNOĞLU YAĞIN ***@***.***>, 10 Haz 2022 Cum, 19:21
tarihinde şunu yazdı:

**Comment by sorenwacker** [comment]
Hi, you should now be able to install the app with pip


    pip install ms-mint-app

and then start the app with

    Mint.py


Unfortunately, the current version of the flask caching library  is not working correctly. So, you will see errors in the console:


> ERROR:flask_caching.backends.filesystemcache:get key 'progress' -> invalid load key, '\x13'.


That only means the progress bar is not working right now. 

A quickstart is available [here](https://lewisresearchgroup.github.io/ms-mint-app/quickstart/)

       

On Windows I would recommend installing Miniconda and install mint with pip.

**Comment by drhilal** [comment]
Hi, I have installed the application, but no action is taken with the mzml
data I downloaded.
The data I downloaded is located at
https://www.metabolomicsworkbench.org/data/DRCCMetadata.php?Mode=Study&StudyID=ST002091&StudyType=MS&ResultType=1.
I'm a Biostatistician and I'm new to Metabolomics so I may be inexperienced
at this. :( Do you have any suggestions for me to find suitable data?.

Also, thanks for your suggestions, I'm installing miniconda and mint.


Sören Wacker ***@***.***>, 10 Haz 2022 Cum, 20:39 tarihinde
şunu yazdı:

**Comment by sorenwacker** [comment]
Looks like we need a file browser to see the content of the files. 

Do you know what MS mode this files used? Is it MS1? 
Do you have a few target definitions at hand? Like mz_values ?

**Comment by sorenwacker** [comment]
It looks like these files are broken. I tried opening them with TOPPView and this is what I see: 

![image](https://user-images.githubusercontent.com/3391614/173140912-1c87df2f-a195-425b-8b9a-b9d47104be89.png)

**Comment by sorenwacker** [comment]
@hilaluzunoglu here is a good dataset: https://www.ebi.ac.uk/metabolights/MTBLS413/descriptors

**Comment by drhilal** [comment]
Thanks! 🙏

23 Haz 2022 Per 17:13 tarihinde Sören Wacker ***@***.***>
şunu yazdı:
