### ISSUE TITLE
rt values in uploaded peaklist file is altered

### ISSUE THREAD

**Issue by Akm789** [LewisResearchGroup/ms-mint-app#28]
Hello,

I tried uploading a peak list file into the demo version of mint. But when the file is uploaded, the values of retention time do not match with the file uploaded. I do not know what is the error. Can you tell me what is wrong with it? I have attached the peak list file I used in the demo mint.
[A_hilic_mint_peaklist.csv](https://github.com/LewisResearchGroup/ms-mint-app/files/9795855/A_hilic_mint_peaklist.csv)

Thank you

Ayush

    MINT version: v0.1.8.3
    OS: Linux-5.4.0-1053-kvm-x86_64-with-glibc2.31
    Versions: ---

**Comment by sorenwacker** [comment]
Hi Ayush,
that is expected behaviour. The RT values are converted from minutes to seconds if rt_unit is not provided, or when rt_unit is set to 
 'min'.
